// <auto-generated />
using System;
using Bwod.OrderAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bwod.OrderAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20220625042909_AddOrderDataTablesOnDB")]
    partial class AddOrderDataTablesOnDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bwod.OrderAPI.Model.OrderDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("count")
                        .HasColumnType("int")
                        .HasColumnName("count");

                    b.Property<int>("order_header_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.Property<int>("product_id")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("product_name")
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.HasKey("id");

                    b.HasIndex("order_header_id");

                    b.ToTable("order_detail");
                });

            modelBuilder.Entity("Bwod.OrderAPI.Model.OrderHeader", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("card_number")
                        .HasColumnType("longtext")
                        .HasColumnName("card_number");

                    b.Property<int>("cart_total_itens")
                        .HasColumnType("int")
                        .HasColumnName("total_itens");

                    b.Property<string>("coupon_code")
                        .HasColumnType("longtext")
                        .HasColumnName("coupon_code");

                    b.Property<string>("cvv")
                        .HasColumnType("longtext")
                        .HasColumnName("cvv");

                    b.Property<DateTime>("date_time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purchase_date");

                    b.Property<string>("email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("expiry_month_year")
                        .HasColumnType("longtext")
                        .HasColumnName("expiry_month_year");

                    b.Property<string>("first_name")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("last_name")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<DateTime>("order_time")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("order_time");

                    b.Property<bool>("payment_status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("payment_status");

                    b.Property<string>("phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<decimal>("purchase_amount")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("purchase_amount");

                    b.Property<string>("user_id")
                        .HasColumnType("longtext")
                        .HasColumnName("user_id");

                    b.HasKey("id");

                    b.ToTable("order_header");
                });

            modelBuilder.Entity("Bwod.OrderAPI.Model.OrderDetail", b =>
                {
                    b.HasOne("Bwod.OrderAPI.Model.OrderHeader", "order_header")
                        .WithMany("order_details")
                        .HasForeignKey("order_header_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order_header");
                });

            modelBuilder.Entity("Bwod.OrderAPI.Model.OrderHeader", b =>
                {
                    b.Navigation("order_details");
                });
#pragma warning restore 612, 618
        }
    }
}
